name: CI pipeline for Juniper
run-name: CI-${{github.run_number}}-${{github.actor}} test ${{github.repository}} triggered by ${{github.event_name}} event
on: [push]

jobs:
  test_juniper:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v6
      - name: setup python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version}}
          cache: 'pip'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: test with pytest
        run: |
          pip install pytest pytest-cov
          pytest --cov=tests --cov-report=xml
      - name: test with ruff
        run: |
          pip install ruff
          ruff clean
          ruff check --output-format=github .
